stages:
  - prep
  - build
  - containers
  - sync

prep:
  image: 'opensuse/tumbleweed:latest'
  stage: prep
  script: 
    - 'zypper -q -n ref && zypper -q -n in buildah'
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - "cd containers && ./build_base.sh"
  
build:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: build
  except:
    - tags
  services:
    - name: 'docker.io/bergamotmonitoring/bergamot-test-ssh:latest'
      alias: 'bergamot-test-ssh'
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - "mvn clean install package deploy -B"
  artifacts:
    paths:
      - 'pom.xml'
      - '*/pom.xml'
      - '*/target/*.jar'
      - '*/target/*.app'

release:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: build
  only:
    - tags
  services:
    - name: 'docker.io/bergamotmonitoring/bergamot-test-ssh:latest'
      alias: 'bergamot-test-ssh'
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - "mvn versions:set -DnewVersion=$CI_COMMIT_TAG -B"
    - "mvn clean install package deploy -B"
  artifacts:
    paths:
      - 'pom.xml'
      - '*/pom.xml'
      - '*/target/*.jar'
      - '*/target/*.app'

containers:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: containers
  script: 
    - 'zypper -q -n ref && zypper -q -n in buildah'
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - 'cd containers && ./build_apps.sh'

sync:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: sync
  script: 
    - 'git status'
    - 'git remote add github "https://intrbiz:${GITHUB_PASS}@github.com/intrbiz/bergamot.git"'
    - 'git push --tags github master'
