stages:
  - prep
  - build

prep:
  image: opensuse/tumbleweed:latest
  stage: prep
  script: 
    - 'zypper -q -n ref && zypper -q -n in buildah'
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - "cd containers && ./build_base.sh"
  
build:
  image: 'bergamotmonitoring/bergamot-build:latest'
  stage: build
  except:
    - tags
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - "mvn clean install package deploy -B"
    - "cd containers && ./build_apps.sh"
  artifacts:
    paths:
      - '*/target/*.jar'

release:
  image: 'bergamotmonitoring/bergamot-build:latest'
  stage: build
  only:
    - tags
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - "mvn versions:set -DnewVersion=$CI_COMMIT_TAG -B"
    - "mvn clean install package deploy -B"
    - "cd containers && ./build_apps.sh"
  artifacts:
    paths:
      - '*/target/*.jar'
