stages:
  - prep
  - build
  - containers
  - sync

prep_x86_64:
  image: 'opensuse/tumbleweed:latest'
  stage: prep
  tags:
    - x86_64
    - docker
  script: 
    - 'zypper -q -n ref && zypper -q -n in buildah cni cni-plugins'
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - "cd containers && ./build_base.sh"
    
prep_arm64:
  stage: prep
  tags:
    - arm64
    - shell
  script: 
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - "cd containers && ./build_base.sh"
  
build:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: build
  tags:
    - x86_64
    - docker
  except:
    - tags
  services:
    - name: 'docker.io/bergamotmonitoring/bergamot-test-ssh:latest'
      alias: 'bergamot-test-ssh'
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - "mvn clean install deploy -B -U"
  artifacts:
    paths:
      - 'pom.xml'
      - '*/pom.xml'
      - '*/target/*.jar'
      - '*/target/*.app'
      - '*/target/*.tar.gz'
      - '*/target/*.sql'

release:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: build
  tags:
    - x86_64
    - docker
  only:
    - tags
  services:
    - name: 'docker.io/bergamotmonitoring/bergamot-test-ssh:latest'
      alias: 'bergamot-test-ssh'
  script: 
    - "mkdir -p $HOME/.m2"
    - "./.settings.sh > $HOME/.m2/settings.xml"
    - "mvn versions:set -DnewVersion=$CI_COMMIT_TAG -B"
    - "mvn clean install deploy -B -U"
  artifacts:
    paths:
      - 'pom.xml'
      - '*/pom.xml'
      - '*/target/*.jar'
      - '*/target/*.app'
      - '*/target/*.tar.gz'
      - '*/target/*.sql'

containers:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: containers
  tags:
    - x86_64
    - docker
  script: 
    - 'zypper -q -n ref && zypper -q -n in buildah cni cni-plugins'
    - 'echo "${DOCKER_PASS}" | buildah login --username "bergamotmonitoring" --password-stdin docker.io'
    - 'cd containers && ./build_apps.sh'

sync:
  image: 'docker.io/bergamotmonitoring/bergamot-build:latest'
  stage: sync
  tags:
    - x86_64
    - docker
  script:
    - 'git checkout $CI_COMMIT_REF_NAME'
    - 'git status'
    - 'git remote add github "https://intrbiz:${GITHUB_PASS}@github.com/intrbiz/bergamot.git"'
    - 'git push --tags github $CI_COMMIT_REF_NAME'
