/* Generated By:JavaCC: Do not edit this line. TimeRangeParserInternalConstants.java */
package com.intrbiz.bergamot.timerange.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TimeRangeParserInternalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGITS = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int DAY = 10;
  /** RegularExpression Id. */
  int DAYOFWEEK = 11;
  /** RegularExpression Id. */
  int MONTH = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<DIGITS>",
    "\":\"",
    "\"-\"",
    "\",\"",
    "\"day\"",
    "<DAYOFWEEK>",
    "<MONTH>",
  };

}
