/* Generated By:JavaCC: Do not edit this line. TimeRangeParserInternal.java */
package com.intrbiz.bergamot.timerange.parser;

import java.util.List;
import java.util.LinkedList;

import com.intrbiz.bergamot.model.timeperiod.TimeRange;
import com.intrbiz.bergamot.model.timeperiod.HourRange;
import com.intrbiz.bergamot.model.timeperiod.ComposedTimeRange;
import com.intrbiz.bergamot.model.timeperiod.DayOfWeekQualifier;
import com.intrbiz.bergamot.model.timeperiod.DayOfMonthQualifier;
import com.intrbiz.bergamot.model.timeperiod.MonthQualifier;
import com.intrbiz.bergamot.model.timeperiod.DayQualifier;
import com.intrbiz.bergamot.model.timeperiod.DateQualifier;
import com.intrbiz.bergamot.model.timeperiod.DayOfWeekInMonthQualifier;
import com.intrbiz.bergamot.model.timeperiod.util.DayOfWeek;
import com.intrbiz.bergamot.model.timeperiod.util.Month;

@SuppressWarnings("all")
public final class TimeRangeParserInternal implements TimeRangeParserInternalConstants {

  final public DayOfWeek readDayOfWeek() throws ParseException {
        Token dayOfWeek;
    dayOfWeek = jj_consume_token(DAYOFWEEK);
      {if (true) return DayOfWeek.valueOf(dayOfWeek.image.toUpperCase());}
    throw new Error("Missing return statement in function");
  }

  final public Month readMonth() throws ParseException {
        Token month;
    month = jj_consume_token(MONTH);
      {if (true) return Month.valueOf(month.image.toUpperCase());}
    throw new Error("Missing return statement in function");
  }

  final public HourRange readHourRange() throws ParseException {
        Token startHour;
        Token startMinute;
        Token stopHour;
        Token stopMinute;
    startHour = jj_consume_token(DIGITS);
    jj_consume_token(COLON);
    startMinute = jj_consume_token(DIGITS);
    jj_consume_token(MINUS);
    stopHour = jj_consume_token(DIGITS);
    jj_consume_token(COLON);
    stopMinute = jj_consume_token(DIGITS);
      {if (true) return new HourRange(Integer.parseInt(startHour.image), Integer.parseInt(startMinute.image), Integer.parseInt(stopHour.image), Integer.parseInt(stopMinute.image));}
    throw new Error("Missing return statement in function");
  }

  final public ComposedTimeRange readHourRanges() throws ParseException {
        ComposedTimeRange ranges = new ComposedTimeRange();
        HourRange range;
    range = readHourRange();
                                  ranges.addRange(range);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      jj_consume_token(COMMA);
      range = readHourRange();
                                  ranges.addRange(range);
    }
      {if (true) return ranges;}
    throw new Error("Missing return statement in function");
  }

  final public ComposedTimeRange readDayOfWeekTimeRange() throws ParseException {
        DayOfWeekQualifier range = new DayOfWeekQualifier();
        DayOfWeek dayOfWeek;
        ComposedTimeRange hours;
    dayOfWeek = readDayOfWeek();
    hours = readHourRanges();
        range.setDayOfWeek(dayOfWeek);
        range.setRanges(hours.getRanges());
        {if (true) return range;}
    throw new Error("Missing return statement in function");
  }

  final public ComposedTimeRange readDayOfMonthTimeRange() throws ParseException {
        DayOfMonthQualifier range = new DayOfMonthQualifier();
        Month month = null;
        Token minus = null;
        Token dayOfMonth;
        ComposedTimeRange hours;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DAY:
      jj_consume_token(DAY);
      break;
    case MONTH:
      month = readMonth();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      minus = jj_consume_token(MINUS);
      break;
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    dayOfMonth = jj_consume_token(DIGITS);
    hours = readHourRanges();
        range.setDayOfMonth(Integer.parseInt(dayOfMonth.image));
        if (minus != null) range.setDayOfMonth( range.getDayOfMonth() * -1 );
        range.setRanges(hours.getRanges());
        {if (true) return month == null ? new DayQualifier(range) : new MonthQualifier(month, range);}
    throw new Error("Missing return statement in function");
  }

  final public ComposedTimeRange readDateTimeRange() throws ParseException {
        DateQualifier range = new DateQualifier();
        Token year;
        Token month;
        Token day;
        ComposedTimeRange hours;
    year = jj_consume_token(DIGITS);
    jj_consume_token(MINUS);
    month = jj_consume_token(DIGITS);
    jj_consume_token(MINUS);
    day = jj_consume_token(DIGITS);
    hours = readHourRanges();
        int mn = Integer.parseInt(month.image);
        if (mn < 1 && mn > 12) {if (true) throw new ParseException("The month '" + month.image + "' must be between 1 and 12");}
        range.setYear(Integer.parseInt(year.image));
        range.setMonth(Month.valueOf(mn - 1));
        range.setDay(Integer.parseInt(day.image));
        range.setRanges(hours.getRanges());
        {if (true) return range;}
    throw new Error("Missing return statement in function");
  }

  final public ComposedTimeRange readDayOfWeekInMonthTimeRange() throws ParseException {
        DayOfWeekInMonthQualifier range = new DayOfWeekInMonthQualifier();
        DayOfWeek dayOfWeek;
        Token minus = null;
        Token dayOfWeekInMonth;
        Month month = null;
        ComposedTimeRange hours;
    dayOfWeek = readDayOfWeek();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      minus = jj_consume_token(MINUS);
      break;
    default:
      jj_la1[3] = jj_gen;
      ;
    }
    dayOfWeekInMonth = jj_consume_token(DIGITS);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MONTH:
      month = readMonth();
      break;
    default:
      jj_la1[4] = jj_gen;
      ;
    }
    hours = readHourRanges();
        range.setMonth(month);
        range.setDayOfWeek(dayOfWeek);
        range.setDayOfWeekInMonth(Integer.parseInt(dayOfWeekInMonth.image));
        if (minus != null) range.setDayOfWeekInMonth( range.getDayOfWeekInMonth() * -1 );
        range.setRanges(hours.getRanges());
        {if (true) return range;}
    throw new Error("Missing return statement in function");
  }

  final public TimeRange readTimeRange() throws ParseException {
        TimeRange range;
    if (jj_2_1(2147483647)) {
      range = readDayOfWeekTimeRange();
    } else if (jj_2_2(2147483647)) {
      range = readDayOfMonthTimeRange();
    } else if (jj_2_3(2147483647)) {
      range = readDayOfWeekInMonthTimeRange();
    } else if (jj_2_4(2147483647)) {
      range = readDateTimeRange();
    } else if (jj_2_5(2147483647)) {
      range = readHourRanges();
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return range;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_3R_5() {
    if (jj_scan_token(DIGITS)) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_scan_token(DIGITS)) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_scan_token(DIGITS)) return true;
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(DIGITS)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_scan_token(DIGITS)) return true;
    if (jj_scan_token(MINUS)) return true;
    if (jj_scan_token(DIGITS)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_scan_token(DIGITS)) return true;
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(DAYOFWEEK)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_5()) return true;
    return false;
  }

  private boolean jj_3R_2() {
    if (jj_3R_7()) return true;
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_6() {
    if (jj_3R_10()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_11()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_3() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(10)) {
    jj_scanpos = xsp;
    if (jj_3R_8()) return true;
    }
    xsp = jj_scanpos;
    if (jj_scan_token(8)) jj_scanpos = xsp;
    if (jj_scan_token(DIGITS)) return true;
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3R_8() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_3()) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(MONTH)) return true;
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_2()) return true;
    return false;
  }

  private boolean jj_3R_4() {
    if (jj_3R_7()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) jj_scanpos = xsp;
    if (jj_scan_token(DIGITS)) return true;
    xsp = jj_scanpos;
    if (jj_3R_9()) jj_scanpos = xsp;
    if (jj_3R_6()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public TimeRangeParserInternalTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[5];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x200,0x1400,0x100,0x100,0x1000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[5];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public TimeRangeParserInternal(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public TimeRangeParserInternal(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new TimeRangeParserInternalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public TimeRangeParserInternal(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new TimeRangeParserInternalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public TimeRangeParserInternal(TimeRangeParserInternalTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(TimeRangeParserInternalTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 5; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[13];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 5; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 13; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
