/* Generated By:JavaCC: Do not edit this line. VirtualCheckExpressionParserInternalConstants.java */
package com.intrbiz.bergamot.virtual.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VirtualCheckExpressionParserInternalConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UUID = 6;
  /** RegularExpression Id. */
  int XOR = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int LOR = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int NE = 13;
  /** RegularExpression Id. */
  int LT = 14;
  /** RegularExpression Id. */
  int LTEQ = 15;
  /** RegularExpression Id. */
  int GT = 16;
  /** RegularExpression Id. */
  int GTEQ = 17;
  /** RegularExpression Id. */
  int STCOMP = 18;
  /** RegularExpression Id. */
  int EDCOMP = 19;
  /** RegularExpression Id. */
  int STARRAY = 20;
  /** RegularExpression Id. */
  int EDARRAY = 21;
  /** RegularExpression Id. */
  int STBRACE = 22;
  /** RegularExpression Id. */
  int EDBRACE = 23;
  /** RegularExpression Id. */
  int SEP = 24;
  /** RegularExpression Id. */
  int HOST = 25;
  /** RegularExpression Id. */
  int SERVICE = 26;
  /** RegularExpression Id. */
  int TRAP = 27;
  /** RegularExpression Id. */
  int HOSTS = 28;
  /** RegularExpression Id. */
  int SERVICES = 29;
  /** RegularExpression Id. */
  int TRAPS = 30;
  /** RegularExpression Id. */
  int RESOURCE = 31;
  /** RegularExpression Id. */
  int CLUSTER = 32;
  /** RegularExpression Id. */
  int POOL = 33;
  /** RegularExpression Id. */
  int ON = 34;
  /** RegularExpression Id. */
  int IN = 35;
  /** RegularExpression Id. */
  int COUNT = 36;
  /** RegularExpression Id. */
  int IS = 37;
  /** RegularExpression Id. */
  int ALL = 38;
  /** RegularExpression Id. */
  int ANY = 39;
  /** RegularExpression Id. */
  int ONE = 40;
  /** RegularExpression Id. */
  int TWO = 41;
  /** RegularExpression Id. */
  int THREE = 42;
  /** RegularExpression Id. */
  int FOUR = 43;
  /** RegularExpression Id. */
  int FIVE = 44;
  /** RegularExpression Id. */
  int SIX = 45;
  /** RegularExpression Id. */
  int SEVEN = 46;
  /** RegularExpression Id. */
  int EIGHT = 47;
  /** RegularExpression Id. */
  int NINE = 48;
  /** RegularExpression Id. */
  int LMORE = 49;
  /** RegularExpression Id. */
  int LLESS = 50;
  /** RegularExpression Id. */
  int OF = 51;
  /** RegularExpression Id. */
  int CASE = 52;
  /** RegularExpression Id. */
  int WHEN = 53;
  /** RegularExpression Id. */
  int THEN = 54;
  /** RegularExpression Id. */
  int ELSE = 55;
  /** RegularExpression Id. */
  int END = 56;
  /** RegularExpression Id. */
  int AS = 57;
  /** RegularExpression Id. */
  int STATUS = 58;
  /** RegularExpression Id. */
  int BOOLEAN = 59;
  /** RegularExpression Id. */
  int INTEGER = 60;
  /** RegularExpression Id. */
  int HEXCHAR = 61;
  /** RegularExpression Id. */
  int ESCAPECHAR = 62;
  /** RegularExpression Id. */
  int UESCAPECHAR = 63;
  /** RegularExpression Id. */
  int STRING = 64;
  /** RegularExpression Id. */
  int QUOTE = 65;
  /** RegularExpression Id. */
  int ENDQUOTE = 67;
  /** RegularExpression Id. */
  int CHAR = 68;
  /** RegularExpression Id. */
  int CNTRLESC = 69;
  /** RegularExpression Id. */
  int HEX = 71;
  /** RegularExpression Id. */
  int HEXESC = 72;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRINGSTATE = 1;
  /** Lexical state. */
  int ESCSTATE = 2;
  /** Lexical state. */
  int HEXSTATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<UUID>",
    "<XOR>",
    "<OR>",
    "\"or\"",
    "<AND>",
    "<NOT>",
    "<EQ>",
    "<NE>",
    "<LT>",
    "<LTEQ>",
    "<GT>",
    "<GTEQ>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"host\"",
    "\"service\"",
    "\"trap\"",
    "\"hosts\"",
    "\"services\"",
    "\"traps\"",
    "\"resource\"",
    "\"cluster\"",
    "\"pool\"",
    "\"on\"",
    "\"in\"",
    "\"count\"",
    "\"is\"",
    "\"all\"",
    "\"any\"",
    "\"one\"",
    "\"two\"",
    "\"three\"",
    "\"four\"",
    "\"five\"",
    "\"six\"",
    "\"seven\"",
    "\"eight\"",
    "\"nine\"",
    "\"more\"",
    "\"less\"",
    "\"of\"",
    "\"case\"",
    "\"when\"",
    "\"then\"",
    "\"else\"",
    "\"end\"",
    "\"as\"",
    "<STATUS>",
    "<BOOLEAN>",
    "<INTEGER>",
    "<HEXCHAR>",
    "<ESCAPECHAR>",
    "<UESCAPECHAR>",
    "<STRING>",
    "\"\\\"\"",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRLESC>",
    "\"u\"",
    "<HEX>",
    "<HEXESC>",
  };

}
