/* Generated By:JavaCC: Do not edit this line. VirtualCheckExpressionParserInternal.java */
package com.intrbiz.bergamot.virtual.parser;

import com.intrbiz.bergamot.model.*;
import com.intrbiz.bergamot.virtual.operator.*;
import com.intrbiz.bergamot.virtual.reference.*;
import com.intrbiz.bergamot.virtual.*;
import java.util.*;

@SuppressWarnings("all")
public final class VirtualCheckExpressionParserInternal implements VirtualCheckExpressionParserInternalConstants {

  final private Status readStatus() throws ParseException {
    Token t;
    t = jj_consume_token(LSTATUS);
      {if (true) return Status.parse(t.image);}
    throw new Error("Missing return statement in function");
  }

  final private UUID readUUID() throws ParseException {
    Token t;
    t = jj_consume_token(LUUID);
      {if (true) return UUID.fromString(t.image);}
    throw new Error("Missing return statement in function");
  }

  final private String readString() throws ParseException {
    Token t;
    t = jj_consume_token(LSTRING);
      {if (true) return t.image.substring(1, t.image.length() -1);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readHost() throws ParseException {
    String name = null;
    UUID id = null;
    HostReference host = null;
    jj_consume_token(HOST);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LUUID:
      id = readUUID();
                                  host = new HostById(id);
      break;
    case LSTRING:
      name = readString();
                                  host = new HostByName(name);
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return new ValueOperator(host);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readService() throws ParseException {
    String name = null;
    String hostName = null;
    UUID id = null;
    ServiceReference service = null;
    HostReference host = null;
    jj_consume_token(SERVICE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LUUID:
      id = readUUID();
                                  service = new ServiceById(id);
      break;
    case LSTRING:
      name = readString();
      jj_consume_token(LON);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case HOST:
        jj_consume_token(HOST);
        break;
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LUUID:
        id = readUUID();
                                                  host = new HostById(id);
        break;
      case LSTRING:
        hostName = readString();
                                                  host = new HostByName(hostName);
        break;
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                          service = new ServiceByName(host, name);
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return new ValueOperator(service);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readParentService() throws ParseException {
    String name = null;
    String hostName = null;
    UUID id = null;
    ServiceReference service = null;
    HostReference host = null;
    jj_consume_token(SERVICE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LUUID:
      id = readUUID();
                                  service = new ServiceById(id);
      break;
    default:
      jj_la1[6] = jj_gen;
      if (jj_2_1(2)) {
        name = readString();
        jj_consume_token(LON);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case HOST:
          jj_consume_token(HOST);
          break;
        default:
          jj_la1[4] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LUUID:
          id = readUUID();
                                                  host = new HostById(id);
          break;
        case LSTRING:
          hostName = readString();
                                                  host = new HostByName(hostName);
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                          service = new ServiceByName(host, name);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LSTRING:
          name = readString();
                          service = new AnonymousService(name);
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
      {if (true) return new ValueOperator(service);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readTrap() throws ParseException {
    String name = null;
    String hostName = null;
    UUID id;
    TrapReference trap = null;
    HostReference host = null;
    jj_consume_token(TRAP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LUUID:
      id = readUUID();
                                  trap = new TrapById(id);
      break;
    case LSTRING:
      name = readString();
      jj_consume_token(LON);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case HOST:
        jj_consume_token(HOST);
        break;
      default:
        jj_la1[8] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LUUID:
        id = readUUID();
                                                  host = new HostById(id);
        break;
      case LSTRING:
        hostName = readString();
                                                  host = new HostByName(hostName);
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                          trap = new TrapByName(host, name);
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return new ValueOperator(trap);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readParentTrap() throws ParseException {
    String name = null;
    String hostName = null;
    UUID id;
    TrapReference trap = null;
    HostReference host = null;
    jj_consume_token(TRAP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LUUID:
      id = readUUID();
                                  trap = new TrapById(id);
      break;
    default:
      jj_la1[13] = jj_gen;
      if (jj_2_2(2)) {
        name = readString();
        jj_consume_token(LON);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case HOST:
          jj_consume_token(HOST);
          break;
        default:
          jj_la1[11] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LUUID:
          id = readUUID();
                                                  host = new HostById(id);
          break;
        case LSTRING:
          hostName = readString();
                                                  host = new HostByName(hostName);
          break;
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                          trap = new TrapByName(host, name);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LSTRING:
          name = readString();
                          trap = new AnonymousTrap(name);
          break;
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
      {if (true) return new ValueOperator(trap);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readCluster() throws ParseException {
    String name = null;
    UUID id = null;
    ClusterReference cluster = null;
    jj_consume_token(CLUSTER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LUUID:
      id = readUUID();
                                  cluster = new ClusterById(id);
      break;
    case LSTRING:
      name = readString();
                                  cluster = new ClusterByName(name);
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return new ValueOperator(cluster);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readResource() throws ParseException {
    String name = null;
    String clusterName = null;
    UUID id = null;
    ClusterReference cluster = null;
    ResourceReference resource = null;
    jj_consume_token(RESOURCE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LUUID:
      id = readUUID();
                                  resource = new ResourceById(id);
      break;
    case LSTRING:
      name = readString();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LON:
        jj_consume_token(LON);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CLUSTER:
          jj_consume_token(CLUSTER);
          break;
        default:
          jj_la1[16] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LUUID:
          id = readUUID();
                                                          cluster = new ClusterById(id);
          break;
        case LSTRING:
          name = readString();
                                                          cluster = new ClusterByName(name);
          break;
        default:
          jj_la1[17] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                                  resource = new ResourceByName(cluster, name);
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return new ValueOperator(null);}
    throw new Error("Missing return statement in function");
  }

  final private ValueOperator readCheck() throws ParseException {
    ValueOperator check;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HOST:
      check = readHost();
      break;
    case SERVICE:
      check = readService();
      break;
    case TRAP:
      check = readTrap();
      break;
    case CLUSTER:
      check = readCluster();
      break;
    case RESOURCE:
      check = readResource();
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return check;}
    throw new Error("Missing return statement in function");
  }

  final private List<ValueOperator> readCheckList() throws ParseException {
    List<ValueOperator> checks = new LinkedList<ValueOperator>();
    ValueOperator check;
    jj_consume_token(STARRAY);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HOST:
    case SERVICE:
    case TRAP:
    case RESOURCE:
    case CLUSTER:
      check = readCheck();
                  checks.add(check);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SEP:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_1;
        }
        jj_consume_token(SEP);
        check = readCheck();
                          checks.add(check);
      }
      break;
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    jj_consume_token(EDARRAY);
      {if (true) return checks;}
    throw new Error("Missing return statement in function");
  }

  final public List<CheckReference> readParents() throws ParseException {
    List<CheckReference> checks = new LinkedList<CheckReference>();
    ValueOperator check;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HOST:
      check = readHost();
      break;
    case CLUSTER:
      check = readCluster();
      break;
    case RESOURCE:
      check = readResource();
      break;
    case SERVICE:
      check = readParentService();
      break;
    case TRAP:
      check = readParentTrap();
      break;
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
                  checks.add(check.getCheck());
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEP:
        ;
        break;
      default:
        jj_la1[24] = jj_gen;
        break label_2;
      }
      jj_consume_token(SEP);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case HOST:
        check = readHost();
        break;
      case CLUSTER:
        check = readCluster();
        break;
      case RESOURCE:
        check = readResource();
        break;
      case SERVICE:
        check = readParentService();
        break;
      case TRAP:
        check = readParentTrap();
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                          checks.add(check.getCheck());
    }
      {if (true) return checks;}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readValue() throws ParseException {
    VirtualCheckOperator value;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STCOMP:
      jj_consume_token(STCOMP);
      value = readExpression();
      jj_consume_token(EDCOMP);
                  value = new BracketOperator(value);
      break;
    default:
      jj_la1[26] = jj_gen;
      if (jj_2_3(2147483647)) {
        value = readCheck();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return value;}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readUnary() throws ParseException {
    VirtualCheckOperator value;
    jj_consume_token(NOT);
    value = readValue();
      {if (true) return new NotOperator(value);}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readAllFunction() throws ParseException {
    List<ValueOperator> checks;
    jj_consume_token(ALL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OF:
      jj_consume_token(OF);
      break;
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    checks = readCheckList();
      {if (true) return new AllFunction(checks);}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readAnyFunction() throws ParseException {
    List<ValueOperator> checks;
    jj_consume_token(ANY);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OF:
      jj_consume_token(OF);
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    checks = readCheckList();
      {if (true) return new AnyFunction(checks);}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readOneOfFunction() throws ParseException {
    List<ValueOperator> checks;
    Status as = null;
    jj_consume_token(ONE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OF:
      jj_consume_token(OF);
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    checks = readCheckList();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      as = readStatus();
      break;
    default:
      jj_la1[30] = jj_gen;
      ;
    }
      {if (true) return new OneOfFunction(checks, as);}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readCountFunction() throws ParseException {
    Status status = null;
    List<ValueOperator> checks;
    Token test = null;
    Token value = null;
    Status as = null;
    jj_consume_token(COUNT);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LSTATUS:
      status = readStatus();
      break;
    default:
      jj_la1[31] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OF:
      jj_consume_token(OF);
      break;
    default:
      jj_la1[32] = jj_gen;
      ;
    }
    checks = readCheckList();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IS:
      jj_consume_token(IS);
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
      test = jj_consume_token(EQ);
      break;
    case NE:
      jj_consume_token(NE);
      break;
    case LT:
      jj_consume_token(LT);
      break;
    case LTEQ:
      jj_consume_token(LTEQ);
      break;
    case GT:
      jj_consume_token(GT);
      break;
    case GTEQ:
      jj_consume_token(GTEQ);
      break;
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    value = jj_consume_token(LINTEGER);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case AS:
      jj_consume_token(AS);
      as = readStatus();
      break;
    default:
      jj_la1[35] = jj_gen;
      ;
    }
      {if (true) return new CountFunction(status, checks, test.image.toLowerCase(), Integer.parseInt(value.image), as);}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readCaseFunction() throws ParseException {
        VirtualCheckOperator check;
        Status status;
        Status as;
        List<CaseOperator.CaseWhen> when = new LinkedList<CaseOperator.CaseWhen>();
        Status elseStatus = null;
    jj_consume_token(CASE);
    jj_consume_token(WHEN);
    check = readExpression();
    jj_consume_token(IS);
    status = readStatus();
    jj_consume_token(THEN);
    as = readStatus();
                          when.add(new CaseOperator.CaseWhen(check, status, as));
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case WHEN:
        ;
        break;
      default:
        jj_la1[36] = jj_gen;
        break label_3;
      }
      jj_consume_token(WHEN);
      check = readExpression();
      jj_consume_token(IS);
      status = readStatus();
      jj_consume_token(THEN);
      as = readStatus();
                          when.add(new CaseOperator.CaseWhen(check, status, as));
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
      elseStatus = readStatus();
      break;
    default:
      jj_la1[37] = jj_gen;
      ;
    }
    jj_consume_token(END);
      {if (true) return new CaseOperator(when, elseStatus);}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readFunction() throws ParseException {
    VirtualCheckOperator operator;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ALL:
      operator = readAllFunction();
      break;
    case ANY:
      operator = readAnyFunction();
      break;
    case ONE:
      operator = readOneOfFunction();
      break;
    case COUNT:
      operator = readCountFunction();
      break;
    case CASE:
      operator = readCaseFunction();
      break;
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return operator;}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readOperator() throws ParseException {
    VirtualCheckOperator operator;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case STCOMP:
    case HOST:
    case SERVICE:
    case TRAP:
    case RESOURCE:
    case CLUSTER:
      operator = readValue();
      break;
    case NOT:
      operator = readUnary();
      break;
    case COUNT:
    case ALL:
    case ANY:
    case ONE:
    case CASE:
      operator = readFunction();
      break;
    default:
      jj_la1[39] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return operator;}
    throw new Error("Missing return statement in function");
  }

  final public VirtualCheckOperator readExpression() throws ParseException {
    VirtualCheckOperator operator;
    operator = readXorExpression();
      {if (true) return operator;}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readXorExpression() throws ParseException {
    VirtualCheckOperator l;
    VirtualCheckOperator r;
    l = readOrExpression();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case XOR:
        ;
        break;
      default:
        jj_la1[40] = jj_gen;
        break label_4;
      }
      jj_consume_token(XOR);
      r = readOrExpression();
                  l = new XorOperator(l, r);
    }
      {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readOrExpression() throws ParseException {
    VirtualCheckOperator l;
    VirtualCheckOperator r;
    l = readAndExpression();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[41] = jj_gen;
        break label_5;
      }
      jj_consume_token(OR);
      r = readAndExpression();
                  l = new OrOperator(l, r);
    }
      {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  final private VirtualCheckOperator readAndExpression() throws ParseException {
    VirtualCheckOperator l;
    VirtualCheckOperator r;
    l = readOperator();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[42] = jj_gen;
        break label_6;
      }
      jj_consume_token(AND);
      r = readOperator();
                 l = new AndOperator(l,r);
    }
      {if (true) return l;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_3R_36() {
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_31() {
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_20() {
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_30() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(LON)) return true;
    return false;
  }

  private boolean jj_3R_18() {
    if (jj_scan_token(RESOURCE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) return true;
    }
    return false;
  }

  private boolean jj_3R_19() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_13() {
    if (jj_3R_18()) return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_3R_17()) return true;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_3R_16()) return true;
    return false;
  }

  private boolean jj_3R_26() {
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_16() {
    if (jj_scan_token(TRAP)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) return true;
    }
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(LON)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    }
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3R_25() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3R_8() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_9()) {
    jj_scanpos = xsp;
    if (jj_3R_10()) {
    jj_scanpos = xsp;
    if (jj_3R_11()) {
    jj_scanpos = xsp;
    if (jj_3R_12()) {
    jj_scanpos = xsp;
    if (jj_3R_13()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_32() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_14() {
    if (jj_scan_token(HOST)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) return true;
    }
    return false;
  }

  private boolean jj_3R_22() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(LON)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(24)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) return true;
    }
    return false;
  }

  private boolean jj_3R_21() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_17() {
    if (jj_scan_token(CLUSTER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) return true;
    }
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(LSTRING)) return true;
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_3R_7()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(LON)) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_29()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_3R_7()) return true;
    if (jj_scan_token(LON)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(24)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_32()) {
    jj_scanpos = xsp;
    if (jj_3R_33()) return true;
    }
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_scan_token(LUUID)) return true;
    return false;
  }

  private boolean jj_3R_15() {
    if (jj_scan_token(SERVICE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    }
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_29()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public VirtualCheckExpressionParserInternalTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[43];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x40,0x1000000,0x40,0x40,0x1000000,0x40,0x40,0x0,0x1000000,0x40,0x40,0x1000000,0x40,0x40,0x0,0x40,0x10000000,0x40,0x20000000,0x40,0x1f000000,0x800000,0x1f000000,0x1f000000,0x800000,0x1f000000,0x20000,0x0,0x0,0x0,0x0,0x0,0x0,0x80000000,0x1f800,0x0,0x0,0x0,0x40000000,0x5f020400,0x80,0x100,0x200,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x10000,0x0,0x10000,0x10000,0x0,0x10000,0x0,0x10000,0x0,0x10000,0x10000,0x0,0x10000,0x0,0x10000,0x10000,0x0,0x10000,0x0,0x10000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x8,0x8,0x200,0x400,0x8,0x0,0x0,0x200,0x20,0x80,0x17,0x17,0x0,0x0,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[3];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public VirtualCheckExpressionParserInternal(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public VirtualCheckExpressionParserInternal(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new VirtualCheckExpressionParserInternalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 43; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 43; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public VirtualCheckExpressionParserInternal(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new VirtualCheckExpressionParserInternalTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 43; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 43; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public VirtualCheckExpressionParserInternal(VirtualCheckExpressionParserInternalTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 43; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(VirtualCheckExpressionParserInternalTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 43; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[57];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 43; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 57; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 3; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
